### ISSUE TITLE
Won't compile, Arduino IDE 1.8.5

### ISSUE THREAD

**Issue by himijendrix24** [qub1750ul/Arduino_L293#2]
**The examples won't compile. Installed via library manager in Arduino IDE 1.8.5.**

**Error Code:**
Arduino: 1.8.5 (Windows 10), Board: "Arduino Nano, ATmega328P"

In file included from C:\Users\MrX\Documents\Arduino\libraries\L293\src/L293.h:15:0,

from C:\Users\MrX\Documents\Arduino\libraries\L293\examples\MotorControl_Demo\MotorControl_Demo.ino:44:

C:\Users\MrX\Documents\Arduino\libraries\L293\src/L293_std.hpp:20:16: warning: inline function 'virtual void L293::forward(uint8_t)' used but never defined

inline void forward( uint8_t _PWMDC = 0 ) override ; ///< Makes the motor to go forward and sets a new speed value

C:\Users\MrX\Documents\Arduino\libraries\L293\src/L293_std.hpp:21:16: warning: inline function 'virtual void L293::back(uint8_t)' used but never defined

inline void back( uint8_t _PWMDC = 0 )  override ;   ///< Makes the motor to go reverse and sets a new speed value

	
In file included from C:\Users\MrX\Documents\Arduino\libraries\L293\src/L293_std.hpp:3:0,

from C:\Users\MrX\Documents\Arduino\libraries\L293\src/L293.h:15,

from C:\Users\MrX\Documents\Arduino\libraries\L293\examples\MotorControl_Demo\MotorControl_Demo.ino:44:

C:\Users\MrX\Documents\Arduino\libraries\L293\src/L293_base.hpp:19:18: warning: inline function 'void L293_base::stop() const' used but never defined

inline void   stop()     const ;        ///< Stops the motor by power reduction

	

In file included from C:\Users\MrX\Documents\Arduino\libraries\L293\src/L293.h:15:0,

from C:\Users\MrX\Documents\Arduino\libraries\L293\examples\MotorControl_Demo\MotorControl_Demo.ino:44:

C:\Users\MrX\Documents\Arduino\libraries\L293\src/L293_std.hpp:22:16: warning: inline function 'virtual bool L293::isForward() const' used but never defined

inline bool isForward() const override ;          ///< Tells the information about the motor that the name says

C:\Users\MrX\Documents\Arduino\libraries\L293\src/L293_std.hpp:23:16: warning: inline function 'virtual bool L293::isReverse() const' used but never defined

inline bool isReverse() const override ;          ///< Tells the information about the motor that the name says

C:\Users\MrX\Documents\Arduino\libraries\L293\src/L293_std.hpp:24:16: warning: inline function 'virtual bool L293::isStopped() const' used but never defined

inline bool isStopped() const override ;          ///< Tells the information about the motor that the name says

In file included from C:\Users\MrX\Documents\Arduino\libraries\L293\src\L293_std.hpp:3:0,

from C:\Users\MrX\Documents\Arduino\libraries\L293\src\L293_std.cpp:1:

C:\Users\MrX\Documents\Arduino\libraries\L293\src\L293_base.hpp:19:18: warning: inline function 'void L293_base::stop() const' used but never defined

inline void   stop()     const ;        ///< Stops the motor by power reduction

C:\Users\MrX\Documents\Arduino\libraries\L293\src\L293_base.hpp:21:19: warning: inline function 'uint8_t L293_base::getPWMDC() const' used but never defined

inline uint8_t getPWMDC()   const ;        ///< Return the effective last set speed value

In file included from C:\Users\MrX\Documents\Arduino\libraries\L293\src\L293_twoWire.hpp:3:0,

from C:\Users\MrX\Documents\Arduino\libraries\L293\src\L293_twoWire.cpp:1:

C:\Users\MrX\Documents\Arduino\libraries\L293\src\L293_base.hpp:19:18: warning: inline function 'void L293_base::stop() const' used but never defined

inline void   stop()     const ;        ///< Stops the motor by power reduction

C:\Users\MrX\Documents\Arduino\libraries\L293\src\L293_base.hpp:21:19: warning: inline function 'uint8_t L293_base::getPWMDC() const' used but never defined

inline uint8_t getPWMDC()   const ;        ///< Return the effective last set speed value

Archiving built core (caching) in: C:\Users\MrX\AppData\Local\Temp\arduino_cache_986469\core\core_arduino_avr_nano_cpu_atmega328_0c812875ac70eb4a9b385d8fb077f54c.a
C:\Users\MrX\AppData\Local\Temp\ccJ1F5xU.ltrans0.ltrans.o: In function `L293::back(unsigned char)':

C:\Users\MrX\Documents\Arduino\libraries\L293\src/L293_std.cpp:39: undefined reference to `L293_base::stop() const'

C:\Users\MrX\Documents\Arduino\libraries\L293\src/L293_std.cpp:42: undefined reference to `L293_base::getPWMDC() const'

C:\Users\MrX\AppData\Local\Temp\ccJ1F5xU.ltrans0.ltrans.o: In function `L293::forward(unsigned char)':

C:\Users\MrX\Documents\Arduino\libraries\L293\src/L293_std.cpp:29: undefined reference to `L293_base::stop() const'

C:\Users\MrX\Documents\Arduino\libraries\L293\src/L293_std.cpp:32: undefined reference to `L293_base::getPWMDC() const'

C:\Users\MrX\AppData\Local\Temp\ccJ1F5xU.ltrans0.ltrans.o: In function `L293::~L293()':

C:\Users\MrX\Documents\Arduino\libraries\L293\src/L293_std.hpp:11: undefined reference to `L293_base::~L293_base()'

C:\Users\MrX\AppData\Local\Temp\ccJ1F5xU.ltrans0.ltrans.o: In function `loop':

C:\Users\MrX\Documents\Arduino\libraries\L293\examples\MotorControl_Demo/MotorControl_Demo.ino:76: undefined reference to `L293_base::stop() const'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino Nano.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by qub1750ul** [comment]
Fixed in release [v4.0.1](https://github.com/qub1750ul/Arduino_L293/releases/tag/v4.0.1)
