### ISSUE TITLE
Can this be used to run IC with two PWM inputs

### ISSUE THREAD

**Issue by ghost** [qub1750ul/Arduino_L293#5]
Hi qub1750ul,

Is it possible to use this library to run two DC motor drivers (such as the DRV8870) that use two PWM inputs to control speed and direction?

I assume it could work with the 3 wire setup and just ignore the enable input.

Regards and have a great day.
George

**Comment by ghost** [comment]
Sorry, I meant Speed input for 3 wire setup

**Comment by qub1750ul** [comment]
Hi gxdeange,

yes indeed it could work as you described, but in this way you lose the ability to control speed.
I believe that using the two wire mode could be much more interesting for you.

Assuming that you're using a DRV8870 or another IC with similar interface, you could connect to the two inputs directly and then drive them using the two wire mode.
The catch with this method is that, depending on the specific wire configuration, the meaning of the PWM duty cycle value changes when you switch the direction signal: in particular the active subperiod and the inactive one switch roles.

e.g. to switch direction without changing speed you should do something like this:
```c++
L293_twoWire m( pwmPin, directionPin );

uint8_t pwmdc = 200 ;

m.forward( pwmdc ) ;
delay( 3000 ) ;
m.reverse( 255 - pwmdc ) ;
```

Actually this is a very interesting idea that could be used transparently by the library, probably in a future rework.

Let me know if this helped.

**Comment by ghost** [comment]
Hi qub1750ul,

Thanks for getting back to me with your advice.

I would like to use this library on a custom brushed DC motor board I designed with the DRV8870 which also incorporates independent direction inputs (via a voltage divider network so you can use a joystick) and variable speed control via a standard potentiometer through the analog inputs. The speed will be infinintly variable across the range of the pot and will be adjustable as the motors are running.
I plan to map the analog input to a pwm output which is why I thought the 3 wire option might be better (as it has two pwm outputs) and simply map but ignore the speed pin as the DRV Speed and direction is determined by which of the pwm input pins has a signal and which one is set to low.

Cheers and have a great day
George
